### ISSUE TITLE
Pass level to prefix function

### ISSUE THREAD

**Issue by enten** [watson/console-log-level#11]
I suggest to pass level when prefix function is called.

### Patch

[`33  -` ~~`if (typeof prefix === 'function') prefix = prefix()`~~](https://github.com/watson/console-log-level/blob/206be0f5030af88dcfab1fc35197708b97c32ccd/index.js#L33)
`33  +` `if (typeof prefix === 'function') prefix = prefix(level)`

### Usage example

```javascript
var log = require('console-log-level')({
  prefix: (lvl) =>`${lvl.toUpperCase()} >`
})

log.info('foo')
log.warn('bar')

// Expected output:
// INFO > foo
// WARN > bar
```

**Comment by watson** [comment]
Thanks 😃 This have now been added and published to npm as v1.4.0
