### ISSUE TITLE
Why print some stuff to stdout and some to stderr

### ISSUE THREAD

**Issue by LinusU** [watson/console-log-level#4]
I think that this behaviour is very counterintuitive. We have had the stdout vs. stderr discussion a number of times in the `debug` library and we decided that stderr is the correct place to log stuff to.

How about switching so that you always log to stderr?

**Comment by watson** [comment]
That's a pretty bold statement :wink: I wouldn't say outputting to stdout isn't counterintuitive - it's how `console.*` works in Node.js and UNIX in general.

But that being said I'm open to suggestions and I understand that it can sometimes be convenient for various reasons to redirect all logging output - and in that case STDERR is a good choice.

I would love to know your current use case?

**Comment by LinusU** [comment]
Hehe, sorry, it was a bit bold :) It just felt very strange that different log levels logged to different places. 

`console.log` vs. `console.error` is named so based on the `stdout` and `stderr`. In the browser, `console.error` actually outputs (in chrome at least) a red line and treats it as an error.

My use case is a cli app which actually outputs data to `stdout, writing anything else there screws up the output.

**Comment by watson** [comment]
I'm thinking maybe I could make an option to redirect all output to stderr instead of a combination of both. I can't come up with out a good name for the option though :disappointed: 

Maybe something like this?

```js
require('console-log-level')({
  stderr: true
})
```

**Comment by lpinca** [comment]
It makes sense, `stderr` for the option name is fine imho.

**Comment by LinusU** [comment]
Well, if we are going to have an option, which I think that we should but I would love for it to default to stderr, I think that option should be a stream.

```javascript
const log = require('console-log-level')(process.stderr)
```

```javascript
const fs = require('fs')
const consoleLogLevel = require('console-log-level')

const log = consoleLogLevel(fs.createWriteStream('myapp.log'))
```

Is there any use case where you would want to log stuff to both stdout and stderr depending on log level?

**Comment by LinusU** [comment]
Being able to put in a stream will help writing better tests as well :)

**Comment by lpinca** [comment]
I think that the idea behind this module is to add the minimum amount of features to make the `console` object a viable logger. If you want proper stream support, there are better alternatives.

> Is there any use case where you would want to log stuff to both stdout and stderr depending on log level?

Yes as stated above, given that `console.log` logs to }stdout} and `console.error` to `stderr` I expect `console-log-level` to do the same.

Anyway wait for @watson to weight in.

**Comment by LinusU** [comment]
Well, I believe that the intent of the original `console` methods have been lost here. The intent wasn't to signify log level, see this bug nodejs/node#3633.

But regardless of how the console works, isn't it very counterintuitive to have the logs end up in different places. It *only* works when looking at it in the terminal. As soon as you pipe it to something or save the log to a file it breaks unless you remember to specify both pipes.

I don't think that "because that's how console works" is a good *use case*, I don't see any real situation where a user would benefit from that particular feature.

Anyhow, that's just my two cents :)

**Comment by lpinca** [comment]
I usually pipe the `stdout` and the `stderr` to two different files.

**Comment by LinusU** [comment]
But would you really want half of your log output in one file, and the other half in the other?

It would also be very hard to know if one line in the first file was logged before or after a line in the other file.

**Comment by lpinca** [comment]
Yes I do, the two file are not necessarily related one to the other.

**Comment by LinusU** [comment]
How are you using the log library when the two aren't related. Sorry if I come across as annoying, I just can't wrap my head around why you would do that...

I'm thinking that it's quite usual to use the different levels to represent verbosity. e.g.

```javascript
function doImportantThing (opts) {
  log.warn('starting important task')
  log.debug('called with %o', opts)

  for (item of opts.items) {
    log.trace('processing item %s', item.id)
    // ...
  }

  log.info('important task is now done')
}
```

It would be very confusing if some of the statements above showed up in a different log file.

Please help me understand what your use case is :)

**Comment by lpinca** [comment]
There is something I only want to log when debugging and I use `log.debug` for this, something that can't fail (`log.info`) which I want to end up in a file and the errors which I want to end up in another file.

**Comment by watson** [comment]
@LinusU Node.js have the build in `console.info`, `console.warn`, `console.error` + the generic `console.log`, and as @lpinca writes and as the name of this module implies, the intent of this module is to use/mimic the native `console.*` functions with the added feature of being able to specify a log-level. The Apache web server for instance - in most default configurations - will output stderr to a separate log (e.g. `/var/log/httpd/error_log`).

That being said, I actually do like your idea of being able to use a stream. I've been looking at your pull request #6 and added a few notes. But in reality this really is a totally different module if we implement these changes - not that I don't like your approach, but it just no longer have anything to do with `console.*`. I would make this into another module and maybe call it `stream-log-level`. You are welcome to do so - if you don't I'll definitely do it, cause it's a nice clean and simple approach :smile:

**Comment by enten** [comment]
## Transport layer

**I suggest to add a transport layer which will be responsible to handle the output logic.**

The main purpose is to **allow to override the output logic**. So, developpers  will be able to choose how to handle output logic. 

We can be **able to multiply transports output** too (write log messages to a file stream, call a remote log service through http requests, etc).

* A transport MUST be **an high-order function** which returns a function called on every log operation.
* A transport CAN be **passed to a logger with the `opts.transport` option**
* `opts.transport` MUST allow function or an array of functions only
* The logger factory MUST have a default transport used when no transports is passed

The logger factory call `opts.transport` to obtain the output handler.
Now, every method of the logger api will use the output handler to do the output job.

Below an example of the usage expected.

```javascript
var createLogger = require('console-log-level')

// The simplest transport logger  which print every 
//  messages with `console.log`
function dummyTransport (level, levelIndex) {
  return function (message, prefix, lvl, lvlIndex) {
    console.log(message)
  }
}

// But we have all the stuff needed to create a transport
// with the behavior of the current output logic
function standardTransport (level, levelIndex) {
  var polyfill = {
    trace: console.info,
    debug: console.info,
    fatal: console.error
  }

  return function (message, prefix, lvl, lvlIndex) {
    if (lvlIndex >= levelIndex) {
      var log = console[lvl] || polyfill[lvl] || console.log
      log(prefix ? util.format(prefix, message) : message)
    }
  }
}

var logger = createLogger({
  level: 'info',
  transport: [dummyTransport, standardTransport]
})

logger.info('foo')
// OUTPUT: "foo" (printed by the dummyTransport)
// OUTPUT: "foo" (printed by the defaultTransport)

logger.debug('bar')
// OUTPUT: "foo" (printed by the dummyTransport)
```

## A try to readjust the current codebase with integrate the transport layer proposal

```javascript
'use strict'

var util = require('util')

exports = module.exports = function (opts) {
  opts = opts || {}
  if (typeof opts.level === 'number') {
    opts.level = exports.levels[opts.level]
  }
  if (typeof opts.prefix === 'string') {
    var strPrefix = opts.prefix
    opts.prefix = function () { return strPrefix }
  }

  var logger = {}
  var level = opts.level || exports.defaultLevel
  var levelIndex = exports.levels.indexOf(level)
  var prefix = opts.prefix || function () {}

  var transports = []
    .concat(opts.transport || exports.defaultTransport)
    .map(function (transport) { return transport(level, levelIndex) })

  exports.levels.forEach(function (lvl, lvlIndex) {
    logger[lvl] = function () {
      var message = util.format.apply(util, arguments)

      transports.forEach(function (transport) {
        transport(message, prefix(lvl, lvlIndex), lvl, lvlIndex)
      })
    }
  })

  return logger
}

exports.levels = ['trace', 'debug', 'info', 'warn', 'error', 'fatal']
exports.defaultLevel = 'info'

exports.defaultTransport = function (level, levelIndex) {
  var polyfill = {
    trace: console.info,
    debug: console.info,
    fatal: console.error
  }

  return function (message, prefix, lvl, lvlIndex) {
    lvlIndex >= levelIndex &&
      (console[lvl] || polyfill[lvl] || console.log)
        (prefix ? util.format(prefix, message) : message)
  }
}
// 52 lines of code instead of 42
```

**Comment by enten** [comment]
So, I wrote [adsl](https://github.com/enten/adsl).

It's like console-log-level with `opts.transport` to handle output logic.
